#!/usr/bin/env bash

cd /usr/local/src
wget http://download.oracle.com/otn-pub/java/jdk/7u5-b05/jdk-7u5-linux-x64.rpm

chmod +x jdk-7u5-linux-x64.rpm
rpm -Uvh jdk-7u5-linux-x64.rpm

cat <<'EOF' >>/etc/profile
export JAVA_HOME=/usr/java/default
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar

EOF
