#!/usr/bin/env bash

USER=mongodb

cd /usr/local/src/
wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.0.2.tgz
tar -zxf mongodb-linux-x86_64-2.0.2.tgz
mv -i mongodb-linux-x86_64-2.0.2 /usr/local/mongodb-linux-x86_64-2.0.2
ln -s /usr/local/mongodb-2.0.2 /usr/local/mongodb

groupadd $USER
id $USER || useradd -s /sbin/nologin -d /usr/local/mongodb -g $USER -M $USER

# /usr/local/mongodb/mongod.conf
cat <<EOF > /usr/local/mongodb/mongod.conf
dbpath=/usr/local/var/mongodb

#logpath=/usr/local/var/log/mongod.log
#logappend=true

# fork and run in background
#fork = true

# only accept local connections
bind_ip = 127.0.0.1

# Enable write ahead logging
journal = true

EOF

# create var directory
mkdir -p /usr/local/var/$USER
chown $USER. /usr/local/var/$USER

# requires djb daemontools
/command/add_service $USER

cat <<EOF >/service/.$USER/run
#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
export PATH

exec 2>&1
exec setuidgid mongodb /usr/local/mongodb/bin/mongod --config /usr/local/mongodb/mongod.conf

EOF

#
echo "to run this service use below command"
echo "# mv -i /service/.$USER /service/$USER"


