#!/usr/bin/env bash

cat >>~/.npmrc <<EOF
root = ~/.npm/libraries
binroot = ~/.npm/bin
manroot = ~/.npm/man
EOF

cat >>/etc/profile <<EOF
export NODE_PATH="/usr/local/lib/node"
export PATH=~/.npm/bin:$PATH
export MANPATH=~/.npm/man:$MANPATH
EOF
source bash_profile

curl http://npmjs.org/install.sh | sh

npm -v
