#!/usr/bin/env bash

SOURCE_DIR=/usr/local/src/nginx1.0.9
USER=nginx
id $USER || useradd -s /sbin/nologin -d /usr/local/nginx -M $USER
mkdir -p /var/tmp/nginx/{proxy,client,fcgi}

cd $SOURCE_DIR
[ -e "$SOURCE_DIR/$NGINX/Makefile" ] && make clean
./configure \
  --conf-path=/etc/nginx/nginx.conf \
  --error-log-path=/var/log/nginx/error.log \
  --pid-path=/var/run/nginx/nginx.pid  \
  --lock-path=/var/lock/nginx.lock \
  --user=nginx \
  --group=nginx \
  --with-http_stub_status_module \
  --with-http_ssl_module \
  --with-http_gzip_static_module \
  --with-http_realip_module \
  --http-log-path=/var/log/nginx/access.log \
  --http-client-body-temp-path=/var/tmp/nginx/client/ \
  --http-proxy-temp-path=/var/tmp/nginx/proxy/ \
  --http-fastcgi-temp-path=/var/tmp/nginx/fcgi/ \
&& make
